"""Справочник GTIN и кэш карточек Нацкаталога

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 01:39:10.511791

"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def _tables():
    return set(sa.inspect(op.get_bind()).get_table_names())


def _create_table(name, *columns, **kw):
    """Переживает собственный обрыв и таблицы, созданные приложением (create_all)."""
    if name not in _tables():
        op.create_table(name, *columns, **kw)


def _create_index(table, name, columns, unique=False):
    existing = {i["name"] for i in sa.inspect(op.get_bind()).get_indexes(table)}
    if name not in existing:
        op.create_index(name, table, columns, unique=unique)



def upgrade():
    _create_table('gtin_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=300), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gtin'),
    sa.UniqueConstraint('supplier_sku')
    )
    _create_table('nk_cards',
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('good_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('card_status', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('tn_ved', sa.String(length=20), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('gtin')
    )
    _create_table('nk_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('nk_requests', 'ix_nk_requests_at', ['at'], unique=False)
    _create_index('nk_requests', 'ix_nk_requests_organization_id', ['organization_id'], unique=False)





def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nk_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nk_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nk_requests_at'))

    op.drop_table('nk_requests')
    op.drop_table('nk_cards')
    op.drop_table('gtin_pairs')
    # ### end Alembic commands ###
