"""sent_quantity в очереди и кабинеты, покрытые расчётом

Revision ID: 22dc047e2f83
Revises: 44ea43d91ca5
Create Date: 2026-09-18 13:21:14.933725

"""
from alembic import op
import sqlalchemy as sa


revision = '22dc047e2f83'
down_revision = '44ea43d91ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recalc_account_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('recalc_account_ids')

    with op.batch_alter_table('dispatch_queue', schema=None) as batch_op:
        batch_op.drop_column('sent_quantity')

    # ### end Alembic commands ###
