"""platform_catalog_item unique by barcode

Revision ID: 3636f44e67d1
Revises: eeccaf673842
Create Date: 2026-09-12 16:42:03.372287

"""
from alembic import op
import sqlalchemy as sa


revision = '3636f44e67d1'
down_revision = 'eeccaf673842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_catalog_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_external_id', type_='unique')
        batch_op.create_unique_constraint('uq_account_barcode', ['account_id', 'barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_catalog_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_barcode', type_='unique')
        batch_op.create_unique_constraint('uq_account_external_id', ['account_id', 'external_id'])

    # ### end Alembic commands ###
