"""остатки 1С на заданное число (EXPORT_STOCK_ON_DATE)

Две новые таблицы под выгрузку остатков на прошедшее число: заявка
(stock_date_snapshots) и сами строки ответа 1С (stock_date_rows). Изменение
чисто аддитивное — существующих таблиц не касается, поэтому откат безопасен:
downgrade просто сносит обе.

Revision ID: 4a9993b59475
Revises: a3f70c5b8e14
Create Date: 2026-09-17 11:54:32.639763

"""
from alembic import op
import sqlalchemy as sa


revision = '4a9993b59475'
down_revision = 'a3f70c5b8e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_date_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'done', 'timeout', name='stockdatestatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('batch_filename', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('result_filename', sa.String(length=128), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_date_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_date_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('stock_date_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('barcodes', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['stock_date_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_date_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_date_rows_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_date_rows_uid_1c'), ['uid_1c'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_date_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_date_rows_uid_1c'))
        batch_op.drop_index(batch_op.f('ix_stock_date_rows_snapshot_id'))

    op.drop_table('stock_date_rows')
    with op.batch_alter_table('stock_date_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_date_snapshots_snapshot_date'))

    op.drop_table('stock_date_snapshots')
    # ### end Alembic commands ###
