"""product reserve

Revision ID: 715e7b25bb23
Revises: 3636f44e67d1
Create Date: 2026-09-12 18:45:05.901222

"""
from alembic import op
import sqlalchemy as sa


revision = '715e7b25bb23'
down_revision = '3636f44e67d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        # server_default='0' — чтобы существующие строки products получили 0
        # при добавлении NOT NULL колонки (иначе апгрейд на непустой базе упадёт).
        batch_op.add_column(sa.Column('reserve', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reserve')

    # ### end Alembic commands ###
