"""login lockout

Revision ID: eeccaf673842
Revises: 
Create Date: 2026-09-11 21:53:24.507604

"""
from alembic import op
import sqlalchemy as sa


revision = 'eeccaf673842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('wb', 'ozon', 'kit', name='platform'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('warehouse_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_connection_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_connection_ok', sa.Boolean(), nullable=True),
    sa.Column('last_connection_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('stock_on_hand', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid_1c')
    )
    op.create_index(op.f('ix_products_article'), 'products', ['article'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('worker_heartbeats',
    sa.Column('worker_name', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_success', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('worker_name')
    )
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_label', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'field_name', name='uq_account_field')
    )
    op.create_table('barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('source_platform', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcodes_barcode'), 'barcodes', ['barcode'], unique=True)
    op.create_table('dispatch_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'error', name='dispatchstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftp_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('warehouse_from', sa.String(length=64), nullable=True),
    sa.Column('warehouse_to', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'done', 'timeout', name='ftptaskstatus'), nullable=False),
    sa.Column('batch_filename', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('result_status', sa.String(length=16), nullable=True),
    sa.Column('result_detail', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_conflicts_barcode'), 'mapping_conflicts', ['barcode'], unique=False)
    op.create_table('platform_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('article', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_account_external_id')
    )
    op.create_index(op.f('ix_platform_catalog_items_barcode'), 'platform_catalog_items', ['barcode'], unique=False)
    op.create_table('processed_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processed', 'cancelled', name='orderprocessstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'order_id', name='uq_account_order')
    )
    op.create_table('reconciliation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('python_stock', sa.Integer(), nullable=False),
    sa.Column('in_flight', sa.Integer(), nullable=False),
    sa.Column('expected_1c', sa.Integer(), nullable=False),
    sa.Column('actual_1c', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('normal', 'auto_plus', 'auto_minus', 'needs_review', name='reconciliationclassification'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('order_on_disabled', 'missing_barcode', name='anomalyreason'), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('new', 'resolved', name='anomalystatus'), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('has_proposal', sa.Boolean(), nullable=False),
    sa.Column('proposal_source', sa.Enum('manual', 'catalog_detected', name='proposalsource'), nullable=True),
    sa.Column('proposal_date', sa.DateTime(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(), nullable=True),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['uid_1c'], ['products.uid_1c'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid_1c', 'account_id', name='uq_product_account')
    )
    op.create_table('test_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_1c', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('info', 'good', 'warn', 'error', name='testloglevel'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_log_entries_uid_1c'), 'test_log_entries', ['uid_1c'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_log_entries_uid_1c'), table_name='test_log_entries')
    op.drop_table('test_log_entries')
    op.drop_table('sync_settings')
    op.drop_table('sync_anomalies')
    op.drop_table('reconciliation_log')
    op.drop_table('processed_orders')
    op.drop_index(op.f('ix_platform_catalog_items_barcode'), table_name='platform_catalog_items')
    op.drop_table('platform_catalog_items')
    op.drop_index(op.f('ix_mapping_conflicts_barcode'), table_name='mapping_conflicts')
    op.drop_table('mapping_conflicts')
    op.drop_table('ftp_tasks')
    op.drop_table('dispatch_queue')
    op.drop_index(op.f('ix_barcodes_barcode'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_table('api_credentials')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_article'), table_name='products')
    op.drop_table('products')
    op.drop_table('platform_accounts')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
