"""Начальная схема программы «Репрайсер»

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 22:42:22.685643

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def _tables():
    return set(sa.inspect(op.get_bind()).get_table_names())


def _create_table(name, *columns, **kw):
    """Миграция обязана переживать собственный обрыв и таблицы, уже созданные
    приложением (`create_all` при старте): на SQLite alembic упавшую миграцию
    не откатывает, и повторный `upgrade head` иначе падал бы навсегда."""
    if name not in _tables():
        op.create_table(name, *columns, **kw)


def _create_index(table, name, columns, unique=False):
    existing = {i["name"] for i in sa.inspect(op.get_bind()).get_indexes(table)}
    if name not in existing:
        op.create_index(name, table, columns, unique=unique)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('last_check_message', sa.Text(), nullable=False),
    sa.Column('catalog_loaded_at', sa.DateTime(), nullable=True),
    sa.Column('catalog_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('audit_log', 'ix_audit_log_at', ['at'], unique=False)

    _create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('usd_rub', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'source', name='uq_rate_date_source')
    )
    _create_index('exchange_rates', 'ix_exchange_rates_rate_date', ['rate_date'], unique=False)

    _create_table('onec_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('article', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', 'item_id', name='uq_onec_barcode_item')
    )
    _create_index('onec_barcodes', 'ix_onec_barcodes_barcode', ['barcode'], unique=False)
    _create_index('onec_barcodes', 'ix_onec_barcodes_item_id', ['item_id'], unique=False)

    _create_table('onec_costs',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    _create_table('onec_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('result_detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('onec_tasks', 'ix_onec_tasks_order_id', ['order_id'], unique=False)
    _create_index('onec_tasks', 'ix_onec_tasks_status', ['status'], unique=False)

    _create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    _create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    _create_table('worker_heartbeats',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    _create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=32), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'field_name', name='uq_cred_account_field')
    )
    _create_table('article_match_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kinds', sa.String(length=128), nullable=False),
    sa.Column('strip_prefix', sa.String(length=64), nullable=True),
    sa.Column('strip_suffix', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    _create_table('manual_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'barcode', name='uq_link_account_barcode')
    )
    _create_table('platform_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('article', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'barcode', name='uq_item_account_barcode')
    )
    _create_index('platform_items', 'ix_platform_items_account_id', ['account_id'], unique=False)
    _create_index('platform_items', 'ix_platform_items_barcode', ['barcode'], unique=False)

    _create_table('price_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usd_rub', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cost_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('new_price', sa.Integer(), nullable=False),
    sa.Column('markup_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('markup_coef', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('block_reason', sa.String(length=16), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('price_changes', 'ix_price_changes_item_id', ['item_id'], unique=False)
    _create_index('price_changes', 'ix_price_changes_status', ['status'], unique=False)

    _create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('markup_coef', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('round_step', sa.Integer(), nullable=False),
    sa.Column('round_minus', sa.Integer(), nullable=False),
    sa.Column('min_markup_coef', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('max_change_percent', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    _create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('manual_price', sa.Integer(), nullable=True),
    sa.Column('last_sent_price', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'account_id', name='uq_price_item_account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_prices')
    op.drop_table('price_rules')
    with op.batch_alter_table('price_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_changes_status'))
        batch_op.drop_index(batch_op.f('ix_price_changes_item_id'))

    op.drop_table('price_changes')
    with op.batch_alter_table('platform_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_items_barcode'))
        batch_op.drop_index(batch_op.f('ix_platform_items_account_id'))

    op.drop_table('platform_items')
    op.drop_table('manual_links')
    op.drop_table('article_match_rules')
    op.drop_table('api_credentials')
    op.drop_table('worker_heartbeats')
    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('onec_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onec_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_onec_tasks_order_id'))

    op.drop_table('onec_tasks')
    op.drop_table('onec_costs')
    with op.batch_alter_table('onec_barcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onec_barcodes_item_id'))
        batch_op.drop_index(batch_op.f('ix_onec_barcodes_barcode'))

    op.drop_table('onec_barcodes')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_rate_date'))

    op.drop_table('exchange_rates')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('accounts')
    # ### end Alembic commands ###
